version: '3'

services:
  my-php:
    build: .
    ports:
      - '${SERVER_PORT}:80'
    volumes:
      - .:/var/www/html
    env_file:
      - .env


  composer:
    image: composer:2.3
    volumes:
      - .:/app